# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  vars,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
    "rtsx_usb_sdmmc"
  ];
  boot.initrd.kernelModules = [
    "tpm_tis"
    "amdgpu"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # --- DISK MANAGEMENT (TPM2 Ready) ---
  boot.initrd.luks.devices."luks-${vars.luksSystemUUID}" = {
    device = "/dev/disk/by-uuid/${vars.luksSystemUUID}";
    allowDiscards = true;
    # Enable TPM2 unlocking
    crypttabExtraOpts = [ "tpm2-device=auto" ];
  };
  boot.initrd.luks.devices."luks-${vars.luksSwapUUID}" = {
    device = "/dev/disk/by-uuid/${vars.luksSwapUUID}";
    allowDiscards = true;
    # Enable TPM2 unlocking
    crypttabExtraOpts = [ "tpm2-device=auto" ];
  };

  fileSystems."/" = {
    device = "/dev/mapper/luks-${vars.luksSystemUUID}";
    fsType = "btrfs";
    options = [
      # UNCOMMENT 'subvol=root' ONLY AFTER manual migration!
      "subvol=root"
      "compress=zstd:3"
      "noatime"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/luks-${vars.luksSystemUUID}";
    fsType = "btrfs";
    neededForBoot = true;
    options = [
      "subvol=home"
      "compress=zstd:3"
      "noatime"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-${vars.luksSystemUUID}";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd:3"
      "noatime"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/srv" = {
    device = "/dev/mapper/luks-${vars.luksSystemUUID}";
    fsType = "btrfs";
    options = [
      "subvol=srv"
      "compress=zstd:3"
      "noatime"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/var/lib/portables" = {
    device = "/dev/mapper/luks-${vars.luksSystemUUID}";
    fsType = "btrfs";
    options = [
      "subvol=var/lib/portables"
      "compress=zstd:3"
      "noatime"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/var/lib/machines" = {
    device = "/dev/mapper/luks-${vars.luksSystemUUID}";
    fsType = "btrfs";
    options = [
      "subvol=var/lib/machines"
      "compress=zstd:3"
      "noatime"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/var/tmp" = {
    device = "/dev/mapper/luks-${vars.luksSystemUUID}";
    fsType = "btrfs";
    options = [
      "subvol=var/tmp"
      "compress=zstd:3"
      "noatime"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/mapper/luks-${vars.luksSystemUUID}";
    fsType = "btrfs";
    neededForBoot = true;
    options = [
      "subvol=persist"
      "compress=zstd:3"
      "noatime"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/${vars.bootUUID}";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    {
      device = "/dev/mapper/luks-${vars.luksSwapUUID}";
      priority = 100;
    }
  ];

  boot.resumeDevice = "/dev/mapper/luks-${vars.luksSwapUUID}";

  # --- HARDWARE PLATFORM ---
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
