# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/mapper/luks-43f71712-badb-4a95-93b1-50bc2ceaf981";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-43f71712-badb-4a95-93b1-50bc2ceaf981".device = "/dev/disk/by-uuid/43f71712-badb-4a95-93b1-50bc2ceaf981";
  boot.initrd.luks.devices."luks-6a6e61c8-3a4f-4223-9a31-47a2c6368b03".device = "/dev/disk/by-uuid/6a6e61c8-3a4f-4223-9a31-47a2c6368b03";

  fileSystems."/home" =
    {
      device = "/dev/mapper/luks-43f71712-badb-4a95-93b1-50bc2ceaf981";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/mapper/luks-43f71712-badb-4a95-93b1-50bc2ceaf981";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/63FA-7885";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [{ device = "/dev/mapper/luks-6a6e61c8-3a4f-4223-9a31-47a2c6368b03"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
